# Generated by Django 3.2.5 on 2021-07-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='county',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.country'),
        ),
        migrations.AlterField(
            model_name='food',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.country'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.city'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.country'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='testapp.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.city'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.country'),
        ),
    ]
