# Generated by Django 3.2.5 on 2021-07-31 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210731_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='food',
            new_name='foods',
        ),
        migrations.AddField(
            model_name='menu',
            name='season',
            field=models.CharField(choices=[('default', 'Стандартне'), ('fall', 'осінь'), ('summer', 'літо'), ('spring', 'весна'), ('winter', 'зима'), ('helloween', 'хелоуін'), ('cristmas', 'різдво')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.country'),
        ),
    ]
