# Generated by Django 3.2.5 on 2021-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210731_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='foods',
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(to='testapp.Food'),
        ),
    ]
