# Generated by Django 3.2.5 on 2021-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(related_name='menus', to='testapp.Food'),
        ),
    ]
